kafka:
  topic:
    user-created-topic: user-created-topic
    user-random-topic: user-random-topic

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
